// models/Prompt.js
import mongoose from 'mongoose';

const promptSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  text: {
    type: String,
    required: true
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  }
}, { timestamps: true });

export const Prompt = mongoose.model('Prompt', promptSchema);
